spring:
  datasource:
    username: root
    password: wu13145..
    url: jdbc:mysql://10.0.12.11:3306/campus_alumni_matching?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  #session 失效时间（分）
  session:
    timeout: 86400
  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    redisson_database : 1

server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        comment: 127.0.0.1
        secure: true
        same-site: none
  address: 0.0.0.0