spring:
  datasource:
    username: root
    password: wu13145
    url: jdbc:mysql://mysql:3306/campus_alumni_matching?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
    #knife4j配置
    path match:
      matching-strategy: ant_path_matcher


  #redis
  redis:
    host: redis_6379
    port: 6379
    database: 0
    redisson_database : 1
    password: wu13145

  #session 失效时间（分）
  session:
    timeout: 86400
    store-type: redis

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.wxl.alumniMatching.domain.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8888
  servlet:
    context-path: /api
    session:
      cookie:
        comment: 47.113.229.30
        secure: true
        same-site: none
  address: 0.0.0.0
  reactive:
    session:
      cookie:
        domain: 47.113.229.30

  #ssl证书配置
  ssl:
    enabled: true
    key-store-password: l9kvn92h    #填写jks-password.txt文件内的密码。
    key-store-type: JKS #JKS格式证书密钥库类型。PFX格式的证书密钥库类型为PKCS12。
    key-store: classpath:ssl/www.cqiewxl.cn.jks   #您需要使用实际的证书名称替换domain_name.jks。