spring:
  datasource:
    username: root
    password: wu13145..
    url: jdbc:mysql://gz-cynosdbmysql-grp-3k1ln4m3.sql.tencentcdb.com:23522/campus_alumni_matching?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
    #knife4j配置
    path match:
      matching-strategy: ant_path_matcher


  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    redisson_database : 1

  #session 失效时间（分）
  session:
    timeout: 86400
    store-type: redis

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.wxl.alumniMatching.domain.entity
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081
  servlet:
    context-path: /api
    session:
      cookie:
        comment: 127.0.0.1
        secure: true
        same-site: none
  address: 0.0.0.0
  reactive:
    session:
      cookie:
        domain: localhost