spring:
  datasource:
    username: root
    password: wu13145
    url: jdbc:mysql://127.0.0.1:3306/campus_alumni_matching_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/
  mvc:
    static-path-pattern: /**
#knife4j配置
    path match:
      matching-strategy: ant_path_matcher


#redis
  redis:
    host: localhost
    port: 6379
    database: 0
    redisson_database : 1

#session 失效时间（分）
  session:
    timeout: 86400
    store-type: redis

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: org.wxl.alumniMatching.domain.entity
  mapper-locations: classpath:mapper/*.xml


#端口号配置
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        comment: localhost
        secure: true
        same-site: none

